<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Add `context` column to `laracrate_file_chunks`.
 *
 * Nullable discriminator for chunks that come from multi-section extractions
 * (e.g. image OCR returning both literal text AND a visual description). Each
 * section produces its own chunk with its own embedding, indexed separately.
 *
 * Conventions:
 *   - NULL          → chunk has no specific context (most cases: PDF body,
 *                     audio transcript, plain text). Default.
 *   - 'text'        → literal text extracted (OCR verbatim).
 *   - 'description' → visual/structural description generated by the extractor.
 *
 * Extractors can use any string they want; consumers should treat unknown
 * values as opaque labels.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('laracrate_file_chunks', function (Blueprint $table) {
            $table->string('context', 30)->nullable()->after('chunk_index');
            $table->index(['file_id', 'context']);
        });
    }

    public function down(): void
    {
        Schema::table('laracrate_file_chunks', function (Blueprint $table) {
            $table->dropIndex(['file_id', 'context']);
            $table->dropColumn('context');
        });
    }
};
